# Problem Set 9, Part One: Due Thursday, April 10 by 8am Eastern Daylight Time

## Name: David Millard

**Show your work on all problems!** Be sure to give credit to any
collaborators, or outside sources used in solving the problems. Note
that if using an outside source to do a calculation, you should use it
as a reference for the method, and actually carry out the calculation
yourself; it’s not sufficient to quote the results of a calculation
contained in an outside source.

Fill in your solutions in the notebook below, inserting markdown and/or code cells as needed.  Try to do reasonably well with the typesetting, but don't feel compelled to replicate my formatting exactly.  **You do NOT need to make random variables blue!**

In [2]:
%matplotlib inline

In [3]:
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (8.0,5.0)
plt.rcParams['font.size'] = 14

### Conover Problems on Chi-Squared Tests

#### Exercise 4.5.2:

A die was cast 600 times with the following results:

| *Occurrence* |  1  |  2  |  3  |  4  |  5  |  6  |
| :----------- | --- | --- | --- | --- | --- | --- |
| *Frequency*  |  87 |  96 | 108 |  89 | 122 |  98 |

Is the die balanced?

$H_0$: $X \sim U(1, 6)$

$H_1$: $X \not\sim U(1, 6)$

$W = 8.579$

$p$-value: $0.12703$

Since $0.12703 > 0.05$, we do not have sufficient evidence to reject $H_0$.

In [41]:
O_i = np.array([87,96,108,89,122,98])
N = np.sum(O_i); c = O_i.shape[0]

pstar_i = np.array([1/6,1/6,1/6,1/6,1/6,1/6])
E_i = N*pstar_i

N, E_i

(600, array([100., 100., 100., 100., 100., 100.]))

In [42]:
W = np.sum((O_i-E_i)**2/E_i)
p = stats.chi2(df=c-1).sf(W)

W, p

(8.579999999999998, 0.12703553284174166)

#### Exercise 4.5.6:

Twenty-six observations were obtained, and the question arose as to
whether they followed a normal distribution with mean 12 and standard
deviation 3. None of the observations were below the lower quartile of
this distribution, and 12 were above the upper quartile. Six were below
the median, and 8 were between the median and the upper quartile. Do
these observations appear to have come from the distribution described?

$H_0$: $X \sim N(12, 3)$

$H_1$: $X \not\sim N(12, 3)$

$W = 11.5384$

$p$-value: $0.009143$

Since $0.009143 < 0.05$, we have significant evidence to reject $H_0$.

In [44]:
O_i = np.array([0,12,6,8])
N = np.sum(O_i); c = O_i.shape[0]

pstar_i = np.array([0.25,0.25,0.25,0.25])
E_i = N*pstar_i

N, E_i

(26, array([6.5, 6.5, 6.5, 6.5]))

In [46]:
W = np.sum((O_i-E_i)**2/E_i)
p = stats.chi2(df=c-1).sf(W)

W, p

(11.538461538461538, 0.009143630523540098)

### Conover Problems on Contingency Tables

#### Exercise 4.2.2:

One horse was selected at random from each of $80$ races and categorized
according to post position (the position assigned to the horse for the
start of the race) and the position in which the horse crossed the
finish line (first, second, etc.).

<table>
    <tr><td></td><td></td><th style="text-align: center" colspan="4">Finish</th></tr>
    <tr><td></td><td></td><th style="text-align: center">1</th><th style="text-align: center">2</th><th style="text-align: center">3</th><th style="text-align: center">Other</th></tr>
    <tr><th style="text-align: left" rowspan="2">Post<br>Position</th><th>1--4</th><td style="text-align: center">8</td><td style="text-align: center">6</td><td style="text-align: center">8</td><td style="text-align: center">16</td></tr>
    <tr><th>5--9</th><td style="text-align: center">3</td><td style="text-align: center">6</td><td style="text-align: center">5</td><td style="text-align: center">28</td></tr>
</table>

Is the horse’s position at the end of the race dependent on post
position? Which test of this section is being used?

$H_0$: $X \perp Y$

$H_1$: $X \not\perp Y$

$W = 6.05289$

$p$-value: $0.109064$

Since $0.109064 > 0.05$, we do not have sufficent evicence to reject $H_0$.

In [52]:
O_ij = np.array([
    [8, 6, 8, 16], 
    [3, 6, 5, 28]    
])

In [53]:
r_i = np.sum(O_ij,axis=1)
c_j = np.sum(O_ij,axis=0)
N = np.sum(O_ij)

r_i, c_j

(array([38, 42]), array([11, 12, 13, 44]))

In [54]:
E_ij = r_i[:,None] * c_j[None,:] / N; E_ij

array([[ 5.225,  5.7  ,  6.175, 20.9  ],
       [ 5.775,  6.3  ,  6.825, 23.1  ]])

In [55]:
w = np.sum((O_ij-E_ij)**2/E_ij)

r=len(r_i); c=len(c_j)
p = stats.chi2(df=(r-1)*(c-1)).sf(w)

w, p

(6.052894473947106, 0.10906496150368931)

#### Exercise 4.2.4:

Three professors are teaching large classes in introductory statistics.
At the end of the semester, they compute grades to see if there are
significant differences in their grading policies.

                                                         
| Professor |  A   |   B  |  C   |  D   |   F  |  WP  |  WF |
| --------- | ---- | ---- | ---- | ---- | ---- | ---- | --- |
| Smith     |$$12$$|$$45$$|$$49$$| $$6$$|$$13$$|$$18$$|$$2$$|
| Jones     |$$10$$|$$32$$|$$43$$|$$18$$| $$4$$|$$12$$|$$6$$|
| White     |$$15$$|$$19$$|$$32$$|$$20$$|$$6$$ | $$9$$|$$7$$|

Are these differences significant? What test are you using? Are the
grades assigned buy Professors Jones and White significantly different?
How would the results be interpreted?

$H_0$: $X \perp Y$

$H_1$: $X \not\perp Y$

$W = 28.9150$

$p$-value: $0.00405$

Since $0.00405 < 0.05$, we have sufficent evidence to reject $H_0$.

In [59]:
O_ij = np.array([
    [12, 45, 49, 6, 13, 18, 2], 
    [10, 32, 43, 18, 4, 12, 6], 
    [15, 19, 32, 20, 6, 9, 7]
])

In [60]:
r_i = np.sum(O_ij,axis=1)
c_j = np.sum(O_ij,axis=0)
N = np.sum(O_ij)

r_i, c_j

(array([145, 125, 108]), array([ 37,  96, 124,  44,  23,  39,  15]))

In [61]:
E_ij = r_i[:,None] * c_j[None,:] / N; E_ij

array([[14.19312169, 36.82539683, 47.56613757, 16.87830688,  8.82275132,
        14.96031746,  5.75396825],
       [12.23544974, 31.74603175, 41.00529101, 14.55026455,  7.60582011,
        12.8968254 ,  4.96031746],
       [10.57142857, 27.42857143, 35.42857143, 12.57142857,  6.57142857,
        11.14285714,  4.28571429]])

In [62]:
w = np.sum((O_ij-E_ij)**2/E_ij)

r=len(r_i); c=len(c_j)
p = stats.chi2(df=(r-1)*(c-1)).sf(w)

w, p

(28.91509065549326, 0.004055965274100453)

#### Problem 4.2.3:

A different method of analyzing contingency tables uses the statistic
$$T' = 2 \sum_{i=1}^r \sum_{j=1}^c O_{ij} \ln(O_{ij}/E_{ij})$$ istead of
$T$, where $\ln$ refers to natural logarithm, found on most calculators.
Otherwise the two test procedures are exactly the same. Use $T'$ in
Exercise 3 to see if the result of the analysis is similar to the result
using $T$. (The two tests are not equivalent in general, even though
they may produce similar results in particular cases.)

Note that Exercise 4.2.3 considers all of the horses in all of the races in three days, and has contingency table
<table>
    <tr><td></td><td></td><th style="text-align: center" colspan="4">Finish</th></tr>
    <tr><td></td><td></td><th style="text-align: center">1</th><th style="text-align: center">2</th><th style="text-align: center">3</th><th style="text-align: center">Other</th></tr>
    <tr><th style="text-align: left" rowspan="2">Post<br>Position</th><th>1--4</th><td style="text-align: center">15</td><td style="text-align: center">14</td><td style="text-align: center">15</td><td style="text-align: center">52</td></tr>
    <tr><th>5--9</th><td style="text-align: center">9</td><td style="text-align: center">10</td><td style="text-align: center">9</td><td style="text-align: center">72</td></tr>
</table>

$H_0$: $X \perp Y$

$H_1$: $X \not\perp Y$

$W = 6.8601$

$p$-value: $0.07649$

Since $0.07649 > 0.05$, we have insufficent evicence to reject $H_0$.

In [84]:
O_ij = np.array([
    [15, 14, 15, 52], 
    [9, 10, 9, 72]    
])

r_i = np.sum(O_ij,axis=1)
c_j = np.sum(O_ij,axis=0)
N = np.sum(O_ij)

E_ij = r_i[:,None] * c_j[None,:] / N

In [85]:
w1 = np.sum((O_ij-E_ij)**2/E_ij)
w2 = 2*np.sum(O_ij*np.log(O_ij/E_ij))

r=len(r_i); c=len(c_j)

p1 = stats.chi2(df=(r-1)*(c-1)).sf(w1)
p2 = stats.chi2(df=(r-1)*(c-1)).sf(w2)

print(f'w1: {w1}, w2: {w2}')
print(f'p1: {p1}, p2: {p2}')

w1: 6.8136783154121865, w2: 6.860148428891671
p1: 0.07807964928550849, p2: 0.07649145487055939
