# Problem Set 10, Part One: Due Thursday, April 17 by 8am Eastern Daylight Time

## Name: David Millard

**Show your work on all problems!** Be sure to give credit to any
collaborators, or outside sources used in solving the problems. Note
that if using an outside source to do a calculation, you should use it
as a reference for the method, and actually carry out the calculation
yourself; it’s not sufficient to quote the results of a calculation
contained in an outside source.

Fill in your solutions in the notebook below, inserting markdown and/or code cells as needed.  Try to do reasonably well with the typesetting, but don't feel compelled to replicate my formatting exactly.  **You do NOT need to make random variables blue!**

In [1]:
%matplotlib inline

In [2]:
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (8.0,5.0)
plt.rcParams['font.size'] = 14

### Conover Problems on $2\times 2$ Contingency Tables

#### Exercise 4.1.8, part (a):

A university received applications from 21 males last year and hired 10,
or 48%. At the same time it received faculty applications from 63 female
applicants and hired 14, or 22%. Does this university appear to have a
higher probability of hiring male applicants than female applicants?
(Use Fisher’s exact test.)

$H_0$: 

$H_1$: 

$T = 10$

$p$-value $= 0.02773$ 

Since $0.02773 < 0.05$, we reject $H_0$.

In [3]:
O_ij = np.array([
    [10, 11],
    [14, 49]
])

In [4]:
r_i = np.sum(O_ij,axis=-1)
c_j = np.sum(O_ij,axis=0)
N=np.sum(O_ij)

r_i, c_j, N

(array([21, 63]), array([24, 60]), 84)

In [5]:
O11 = O_ij[0,0] 
r1 = r_i[0]
c1 = c_j[0]

p = stats.hypergeom(N, c1, r1).sf(O11 - 1)

O11, p

(10, 0.027736184660322426)

#### Followup:

Repeat the calculation of the previous problem using the one-sided test
for differences in probability of hiring for male and female candidates.

$p$-value $= 0.0283$ 

Since $0.0283 < 0.05$, we reject $H_0$.

In [6]:
r2 = r_i[1]
c2 = c_j[1]
O11_x = np.arange(r1+1)
O21_y = np.arange(r2+1)

O11_x,O21_y

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]))

In [15]:
c1_xy = O11_x[:,None] + O21_y[None,:]; c2_xy = N - c1_xy
stat_xy = np.round((N*O11_x[:,None]-r1*c1_xy)/np.sqrt(c1_xy*c2_xy+1e-12),8)
mystat = np.round((N*O11-r1*c1)/np.sqrt(c1*c2+1e-12),8)

mystat

8.85437745

In [8]:
np.sum(stat_xy<=-np.abs(mystat)), np.sum(stat_xy>=np.abs(mystat))

(415, 415)

In [13]:
p1_p = np.linspace(0,1,1000)
pmf_xyp = stats.binom(r1,p1_p[None,None,:]).pmf(O11_x[:,None,None])*stats.binom(r2,p1_p[None,None,:]).pmf(O21_y[None,:,None])
plower_p = np.sum((stat_xy<=mystat)[:,:,None]*pmf_xyp,axis=(0,1))
pupper_p = np.sum((stat_xy>=-mystat)[:,:,None]*pmf_xyp,axis=(0,1))

In [26]:
min(plower_p), max(pupper_p-plower_p)

(0.9716741000249779, 0.028325310546135962)

Which test is appropriate if the university has 24 positions to fill?

Fishers test would be more approate as Fisher’s given both the row and column margins are fixed.

Suppose instead of hiring, the data referred to individual faculty
members being promoted in rank.
Which test would be appropriate then?

We would use the test for equality of proportions, because the margins are not fixed numbers.

#### Problem 4.2.2:

Show that if $r=2$ and $c=2$, Equation 4 \[of section 4.2\] is
equivalent to Equation 4.1.1 squared
$$T = \frac{N(O_{11}O_{12}-O_{21}O_{22})^2}{n_1n_2C_1C_2}$$
[Note that the equation above is correct; the statement printed in Conover has a typo, and is missing the square in $(O_{11}O_{12}-O_{21}O_{22})^2$.]

\begin{align}
    T &= \sum^r_{i=1}\sum^c_{j=1}\frac{(O_{ij}-E_{ij})^2}{E_{ij}}, \quad \text{where} \quad E_{ij}=\frac{n_i C_j}{N} \\
      &= \frac{(O_{11}-E_{11})^2}{E_{11}} + \frac{(O_{12}-E_{12})^2}{E_{12}} + \frac{(O_{21}-E_{21})^2}{E_{21}} + \frac{(O_{22}-E_{22})^2}{E_{22}} \\
      &= \frac{N(O_{11}-E_{11})^2}{n_1 C_1} + \frac{N(O_{12}-E_{12})^2}{n_1 C_2} + \frac{N(O_{21}-E_{21})^2}{n_2 C_1} + \frac{N(O_{22}-E_{22})^2}{n_2 C_2} \\
      &= \frac{N n_2 C_2 (O_{11}-E_{11})^2}{n_1 C_1 n_2 C_2} + \frac{N n_2 C_1 (O_{12}-E_{12})^2}{n_2 C_1 n_1 C_2} + \frac{N n_1 C_2 (O_{21}-E_{21})^2}{n_1 C_2 n_2 C_1} + \frac{N n_1 C_1 (O_{22}-E_{22})^2}{n_1 C_1 n_2 C_2} \\
      &= \frac{N \left( n_2 C_2 (O_{11}-\frac{n_1 C_1}{N})^2 + n_2 C_1 (O_{12}-\frac{n_1 C_2}{N})^2 + n_1 C_2 (O_{21}-\frac{n_2 C_1}{N})^2 + n_1 C_1 (O_{22}-\frac{n_2 C_2}{N})^2 \right)}{n_1 n_2 C_1 C_2} \\
      &= \frac{N \left( n_2 C_2 \left(O_{11}-\frac{n_1 C_1}{N}\right)^2 + n_2 C_1 \left(O_{12}-\frac{n_1 C_2}{N}\right)^2 + n_1 C_2 \left(O_{21}-\frac{n_2 C_1}{N}\right)^2 + n_1 C_1 \left(O_{22}-\frac{n_2 C_2}{N}\right)^2 \right)}{n_1 n_2 C_1 C_2} \\
      &= \frac{N}{n_1 n_2 C_1 C_2} \Bigg[
        n_2 C_2 \left( O_{11}^2 - 2 O_{11} \cdot \frac{n_1 C_1}{N} + \left(\frac{n_1 C_1}{N}\right)^2 \right)
        + n_2 C_1 \left( O_{12}^2 - 2 O_{12} \cdot \frac{n_1 C_2}{N} + \left(\frac{n_1 C_2}{N}\right)^2 \right) \notag \\
      &\quad\quad + n_1 C_2 \left( O_{21}^2 - 2 O_{21} \cdot \frac{n_2 C_1}{N} + \left(\frac{n_2 C_1}{N}\right)^2 \right)
        + n_1 C_1 \left( O_{22}^2 - 2 O_{22} \cdot \frac{n_2 C_2}{N} + \left(\frac{n_2 C_2}{N}\right)^2 \right)
      \Bigg] \\
      &= \frac{N}{n_1 n_2 C_1 C_2} \Bigg[
        n_2 C_2 O_{11}^2 + n_2 C_1 O_{12}^2 + n_1 C_2 O_{21}^2 + n_1 C_1 O_{22}^2 \notag \\
      &\quad - 2 \left( O_{11} n_2 C_2 \cdot \frac{n_1 C_1}{N} + O_{12} n_2 C_1 \cdot \frac{n_1 C_2}{N}
                     + O_{21} n_1 C_2 \cdot \frac{n_2 C_1}{N} + O_{22} n_1 C_1 \cdot \frac{n_2 C_2}{N} \right) \notag \\
      &\quad + \left( \frac{n_1^2 C_1^2 n_2 C_2}{N^2} + \frac{n_1^2 C_2^2 n_2 C_1}{N^2}
                     + \frac{n_2^2 C_1^2 n_1 C_2}{N^2} + \frac{n_2^2 C_2^2 n_1 C_1}{N^2} \right)
      \Bigg] \\
      &= \frac{N}{n_1 n_2 C_1 C_2} \left( n_2 C_2 O_{11}^2 + n_2 C_1 O_{12}^2 + n_1 C_2 O_{21}^2 + n_1 C_1 O_{22}^2 \right. \notag \\
      &\quad\left. - 2 \cdot \frac{n_1 n_2 C_1 C_2}{N} (O_{11} + O_{12} + O_{21} + O_{22})
      + \frac{n_1 n_2 C_1 C_2}{N^2} (n_1 C_1 + n_1 C_2 + n_2 C_1 + n_2 C_2)
      \right)\\
      &= \frac{N(O_{11} O_{22} - O_{12} O_{21})^2}{n_1 n_2 C_1 C_2}
\end{align}

### Conover Problems on the Median Test

#### Exercise 4.3.2:

A number of oil leases were auctioned to the highest bidder. Each lease
received one or more sealed bids. Test the hypothesis that the leases
that eventually became producers of oil have the same median number of
bids as the leases that never produced oil. A random sample of each type
of lease is given below:

|                 |**Number of Bids on Each Lease**      |
| --------------- | ------------------------------------ |
|   *Producers*   |6, 3, 1, 14, 8, 9, 12, 1, 3, 2, 1, 7  |
|  *Nonproducers* |6, 2, 1, 1, 3, 1, 2, 4, 8, 1, 2       |

$H_0$: 

$H_1$: 

$T = 1.24458$

$p$-value $= 0.26458$ 

Since $0.26458 > 0.05$, we fail to reject $H_0$.

In [4]:
x_j_k = [
    np.array([ 6, 3, 1, 14, 8, 9, 12, 1, 3, 2, 1, 7 ]),
    np.array([ 6, 2, 1, 1, 3, 1, 2, 4, 8, 1, 2])
]
grandmedian=np.median(np.concatenate(x_j_k)); grandmedian

3.0

In [8]:
O1_j = np.array([np.sum(xj_k>grandmedian) for xj_k in x_j_k])
O2_j = np.array([np.sum(xj_k<=grandmedian) for xj_k in x_j_k])

r1 = np.sum(O1_j)
r2 = np.sum(O2_j)
c_j = O1_j + O2_j
N=r1+r2
c=len(c_j)

print(f'r1: {r1}, r2: {r2}, c: {c}')

r1: 9, r2: 14, c: 2


|                |$$j=0$$|$$j=1$$|Total|
|   ------:      | :---: | :---: | :-- |
| $$>\tilde{X}$$ |    6  |    3  |  9  |
|$$\le\tilde{X}$$|    6  |    8  | 14  |
|    **Total**   |   12  |   11  | 23  |

In [10]:
T = N**2/(r1*r2) * np.sum((O1_j-r1*c_j/N)**2/c_j)
p = stats.chi2(df=c-1).sf(T)

T, p

(1.244588744588744, 0.2645885200574476)

#### Exercise 4.3.6:

One hundred army recruits were randomly assigned to four drill sergeants
in boot camp. At the end of boot camp 84 recruits remained, and their
performance in the obstacle course was times. For Sergeant Adams, 11 of
his 20 recruits performed above the median. For Sergeant Baker, 8 of her
22 recruits performed above the median. Sergeant Callahan had 8 of his
20, and Sergeant Davis had 15 perform above the median. Is there a
significant difference in the performance results for the four drill
sergeants?

$H_0$: 

$H_1$: 

$T = 5.54$

$p$-value $= 0.1359$ 

Since $0.1359 > 0.05$, we fail to reject $H_0$.

In [21]:
x_j_k = np.array([20, 22, 20, (84-(20+22+20))])
O1_j = np.array([11, 8, 8, 15])
O2_j = x_j_k - O1_j

r1 = np.sum(O1_j)
r2 = np.sum(O2_j)
c_j = O1_j + O2_j
N=r1+r2
c=len(c_j)

print(f'r1: {r1}, r2: {r2}, c: {c}')

r1: 42, r2: 42, c: 4


In [22]:
T = np.sum((O1_j-O2_j)**2/c_j)
p = stats.chi2(df=c-1).sf(T)

T, p

(5.545454545454546, 0.1359450685758528)