# Problem Set 0: Due Thursday, January 16 by 9:15m Eastern Standard Time

## Name: David Millard

This problem set is to give a little bit of practice entering your answers in markdown, and executing basic Python commands.  You won't be graded on it, but you should submit it to MyCourses by the due date, which will give you access to the solutions.

Fill in your solutions in the notebook below, inserting markdown and/or code cells as needed.  Try to do reasonably well with the typesetting, but don't feel compelled to replicate my formatting exactly.  **You do NOT need to make random variables blue!**

In [1]:
%matplotlib inline

In [2]:
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (8.0,5.0)
plt.rcParams['font.size'] = 14

## Markdown Practice

**(a)** The formula for the sample mean $\overline{x}$ of a dataset $\{x_i|i=1,\ldots,n\}\equiv\{x_1,x_2,\ldots,x_n\}$ is
$$
\overline{x} = \frac{1}{n} \sum_{i=1}^n x_i
$$
What is the formula for the sample variance $s^2$?  (You may use $\overline{x}$ in your answer.)

$$s^2 = \frac{1}{n-1}\sum^n_{i=1}(x_i - \bar{x})^2$$

**(b)** The formula for the expectation value (also known as the mean) $\mu=E(\color{royalblue}{X})$ of a continuous random variable with probability density function (pdf) $f(x)$ is
$$
E(\color{royalblue}{X}) = \mu = \int_{-\infty}^{\infty} x\,f(x)\,dx
$$
What is the formula for the variance $\operatorname{Var}(\color{royalblue}{X})$ (sometimes written $\sigma^2$ or $\sigma_X^2$) of $\color{royalblue}{X}$?  (You may use $\mu$ in your answer.)

$$\text{Var}(X) = \sigma^2 = E\left[\left(X - E[X]\right)^2\right] = E[X^2] - E[X]^2$$

## Python Practice

**(a)**  Define an array

In [3]:
A_i = np.arange(5)

Check the dimensions of the array with

In [4]:
A_i.shape

(5,)

and display its contents with

In [5]:
print(A_i)

[0 1 2 3 4]


or view it in a way that also reminds you it's an array with

In [6]:
A_i

array([0, 1, 2, 3, 4])

Also, access the initial element with

In [7]:
A_i[0]

0

(python indexes from zero). If you want the
last element you can use

In [8]:
A_i[-1]

4

What happens if you ask for

In [9]:
A_i[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

Why did that not work?

The array only has 5 elements. When we do `A_i[5]` we are trying to access the 6th element which doesn't exist.

**(b)** Define another array with

In [10]:
B_i = np.ones(5)

check its shape, and display or view its contents.

In [11]:
B_i.shape, B_i

((5,), array([1., 1., 1., 1., 1.]))

One of the nice things
about NumPy is that arithmetic operations are vectorized. (This is
faster than looping over the elements in Python because the
operation is coded up in C.) Define

In [12]:
C_i = A_i + B_i

and show its shape and contents.

In [13]:
C_i.shape, C_i

((5,), array([1., 2., 3., 4., 5.]))

**(c)** You can also add indices to arrays. There are a lot of variants of the syntax, but here’s my favorite. Define

In [14]:
A_xi = A_i[None,:]
E_j = 10.*np.arange(3)
E_jx = E_j[:,None]

and show the shape and contents of `A_xi`, `E_j`, and `E_jx`.

In [15]:
print(A_xi.shape, A_xi)
print(E_j.shape, E_j)
print(E_jx.shape, E_jx)

(1, 5) [[0 1 2 3 4]]
(3,) [ 0. 10. 20.]
(3, 1) [[ 0.]
 [10.]
 [20.]]


**(d)**  Now see what happens when you define

In [16]:
F_ji = A_xi + E_jx

and show its shape and contents.

In [17]:
F_ji.shape, F_ji

((3, 5),
 array([[ 0.,  1.,  2.,  3.,  4.],
        [10., 11., 12., 13., 14.],
        [20., 21., 22., 23., 24.]]))

This is known as **array broadcasting**. What is `F_ji[1,3]`?

In [18]:
F_ji[1,3]

13.0

**(e)** You can also remove indices by taking the sum (or product, or
    average, or various other operations) along one of the “axes” of
    the array. For example, try

In [19]:
 G_i = F_ji.sum(axis=0)

and show its shape and contents.

In [20]:
G_i.shape, G_i

((5,), array([30., 33., 36., 39., 42.]))